const generateUnit = require('./generate_all');

const u = {
  unit: 13,
  title: 'Unit 13: Two Different Forms of British Leisure Life',
  words: [
    { word: 'leisure', pos: 'n.', defVi: 'thời gian rảnh rỗi' },
    { word: 'conservative', pos: 'a.', defVi: 'bảo thủ' },
    { word: 'nature', pos: 'n.', defVi: 'bản chất' },
    { word: 'position', pos: 'n.', defVi: 'vị trí, lập trường, quan điểm' },
    { word: 'elite', pos: 'n.', defVi: 'nhóm tinh hoa' },
    { word: 'demonstrate', pos: 'v.', defVi: 'bày tỏ, biểu lộ' },
    { word: 'respect', pos: 'n.', defVi: 'khía cạnh' },
    { word: 'VIP (very important person)', pos: '', defVi: 'nhân vật quan trọng' },
    { word: 'Pancake Race', pos: '', defVi: 'cuộc thi vào ngày thứ ba trước tuần chay, ngày ăn bánh kếp theo truyền thống' },
    { word: 'start with', pos: '', defVi: 'bắt đầu bằng' },
    { word: 'around', pos: 'prep.', defVi: 'khoảng' },
    { word: 'exclusive', pos: 'a.', defVi: 'dành riêng, đặc quyền' },
    { word: 'parliament', pos: 'n.', defVi: 'nghị viện' },
    { word: 'in session', pos: '', defVi: 'đang phiên họp' },
    { word: 'traditional', pos: 'a.', defVi: 'thuộc truyền thống' },
    { word: 'pirate', pos: 'n.', defVi: 'tên cướp biển' },
    { word: 'informal', pos: 'a.', defVi: 'thân mật' },
    { word: 'object', pos: 'n.', defVi: 'mục đích' },
    { word: 'dine', pos: 'v.', defVi: 'ăn cơm, dùng bữa (trưa, chiều)' },
    { word: 'wine', pos: 'v.', defVi: 'uống rượu' },
    { word: 'intercourse', pos: 'n.', defVi: 'sự giao thiệp' },
    { word: 'interfere with', pos: '', defVi: 'gây trở ngại, can thiệp' },
    { word: 'rigorous', pos: 'a.', defVi: 'nghiêm khắc, nghiêm ngặt' },
    { word: 'pursuit', pos: 'n.', defVi: 'sự theo đuổi' },
    { word: 'Executive Committee', pos: '', defVi: 'Ban điều hành' },
    { word: 'antagonist', pos: 'n.', defVi: 'người đối lập, người phản đối' },
    { word: 'engage in', pos: '', defVi: 'tham gia vào' },
    { word: 'unfettered', pos: 'a.', defVi: 'tự do, không bị ràng buộc' },
    { word: 'amicable', pos: 'a.', defVi: 'thân ái, thân mật, thân tình' },
    { word: 'tradition', pos: 'n.', defVi: 'truyền thống' },
    { word: 'originate from', pos: '', defVi: 'bắt nguồn từ' },
    { word: 'napkin', pos: 'n.', defVi: 'khăn ăn' },
    { word: 'carve', pos: 'v.', defVi: 'chạm, khắc' },
    { word: 'plain', pos: 'a.', defVi: 'giản dị, đơn sơ' },
    { word: 'limited to', pos: '', defVi: 'giới hạn (ở số lượng)' },
    { word: 'prominent', pos: 'a.', defVi: 'xuất chúng, lỗi lạc' },
    { word: 'the Commons', pos: '', defVi: 'Hạ viện (Anh)' },
    { word: 'the Lords', pos: '', defVi: 'Thượng viện (Anh)' },
    { word: 'distinguished', pos: 'a.', defVi: 'ưu tú, xuất sắc, lỗi lạc' },
    { word: 'point of view', pos: '', defVi: 'quan điểm' },
    { word: 'in contrast with', pos: '', defVi: 'tương phản với' },
    { word: 'popular', pos: 'a.', defVi: 'phổ biến' },
    { word: 'Lent', pos: '', defVi: 'tuần chay' },
    { word: 'occur', pos: 'v.', defVi: 'xảy ra' },
    { word: 'reminder', pos: 'n.', defVi: 'điều nhắc nhở' },
    { word: 'consumption', pos: 'n.', defVi: 'sự tiêu thụ' },
    { word: 'use up', pos: '', defVi: 'sử dụng hết' },
    { word: 'frugal', pos: 'a.', defVi: 'tiết kiệm, thanh đạm' },
    { word: 'toss', pos: 'v.', defVi: 'ném' },
    { word: 'observe', pos: 'v.', defVi: 'tuân thủ' },
    { word: 'verger', pos: 'n.', defVi: 'người cai quản giáo đường, người cầm gậy giám mục' },
    { word: 'procession', pos: 'n.', defVi: 'đám rước' },
    { word: 'Westminster Abbey', pos: '', defVi: 'Tu viện Westminster' },
    { word: 'competitor', pos: 'n.', defVi: 'người tham gia cuộc thi' },
    { word: 'get hold of', pos: '', defVi: 'nắm, chộp' },
    { word: 'portion', pos: 'n.', defVi: 'phần, phần chia' },
    { word: 'scramble', pos: 'n.', defVi: 'sự tranh cướp, sự tranh giành' },
    { word: 'guinea', pos: 'n.', defVi: 'đồng ghinê (đồng tiền vàng xưa của Anh, có giá trị tương đương 21 silinh)' },
    { word: 'fund', pos: 'n.', defVi: 'quỹ' },
    { word: 'for one\\\'s part', pos: '', defVi: 'về phần mình' },
    { word: 'spectacular', pos: 'a.', defVi: 'ngoạn mục' },
    { word: 'custom', pos: 'n.', defVi: 'tập quán, tập tục' },
    { word: 'annual', pos: 'a.', defVi: 'hàng năm' },
    { word: 'frying pan', pos: '', defVi: 'chảo chiên' },
    { word: 'contain', pos: 'v.', defVi: 'chứa, đựng' },
    { word: 'sizzling', pos: 'a.', defVi: 'nóng sôi xèo xèo' },
    { word: 'keep', pos: 'v.', defVi: 'tuân theo' },
    { word: 'parish', pos: 'n.', defVi: 'giáo khu' },
    { word: 'prior to', pos: '', defVi: 'trước' },
    { word: 'apron', pos: 'n.', defVi: 'tạp dề' },
    { word: 'scarf', pos: 'n.', defVi: 'khăn quàng cổ' },
    { word: 'loose-fitting', pos: 'a.', defVi: 'rộng thùng thình' },
    { word: 'bar', pos: 'v.', defVi: 'cấm' },
    { word: 'spurt', pos: 'n.', defVi: 'chặng nước rút' },
    { word: 'optional', pos: 'a.', defVi: 'tùy chọn' },
    { word: 'serve', pos: 'v.', defVi: 'phục vụ' },
    { word: 'hail', pos: 'v.', defVi: 'hoan hô, hoan nghênh' },
    { word: 'champion', pos: 'n.', defVi: 'nhà vô địch' },
    { word: 'aristocratic', pos: 'a.', defVi: 'thuộc quý tộc' },
    { word: 'purely', pos: 'ad.', defVi: 'thuần túy' },
    { word: 'participant', pos: 'n.', defVi: 'người tham gia' },
    { word: 'throw light on', pos: '', defVi: 'làm rõ thêm, làm sáng tỏ' }
  ],
  story: `<h1 style="color: #d6334f; font-size: 2.5rem; font-weight: bold; margin-bottom: 1.5rem; line-height: 1.2;">Two Different Forms of British Leisure Life</h1>
  <p style="margin-bottom: 1rem;">British people are always famous for their conservative nature. Nevertheless, they also have some interesting ways to enjoy themselves. Of course, because of their different positions, the social elite and common people demonstrate different tastes in this respect. If the organized leisure, the Club, is for the VIPs, then the amusement like the Pancake Race is for the commons.</p>
  <p style="margin-bottom: 1rem;">Club life started with coffee drinking which began around 1650. Among the most exclusive and famous clubs of London, the Other Club occupies a special position. It was founded in 1911 by Sir Winston Churchill and F. E. Smith. Members of this club gather for dinner once a month when Parliament is in session and their traditional meeting place is the Pirate Room of the Savoy Hotel. These meetings are very private and informal. The Club has only three rules: 1. The object is to dine, wine and talk; 2. Nothing in the intercourse of the members shall be allowed to interfere with the full rigorous pursuit of party politics; 3. The names of the members of the Executive Committee must remain to be unknown.</p>
  <p style="margin-bottom: 1rem;">Political antagonists, who may never be seen to say a word to each other in public, may dine side by side here and engage in unfettered and amicable conversation. The Other Club is rich in traditions. Many of them originated from Sir Winston Churchill. At his command, a large wooden and black cat was seated near him at dinner with a napkin tied around its neck. The name of the black cat is Kaspar. It was designed and carved from a piece of plain tree in 1926 and was placed near to Sir Winston whenever there were only thirteen at table.</p>
  <p style="margin-bottom: 1rem;">Limited to fifty, the list of membership includes prominent members of the Commons and the Lords and other distinguished people. It is a non-political club and was given the name the Other Club because it aims always to hear the other man's point of view.</p>
  <p style="margin-bottom: 1rem;">In contrast with the Other Club there is the popular Pancake Day. It is on the first day of Lent, and usually occurs between February 2 and March 8. It is believed to be a reminder of the days when the consumption of butter and eggs was forbidden during Lent and housewives were anxious to use up all they had left before the start of the frugal period.</p>
  <p style="margin-bottom: 1rem;">At Westminster School, London, the practice of tossing a pancake is carefully observed. Led by a verger, a pancake is carried in procession from Westminster Abbey to the school. The cook, all in white, tosses it high in the air over the heads of young competitors in the school hall and the boy getting hold of the largest portion of it in the scramble, receives a guinea from Abbey funds. The cook is given two guineas for his part.</p>
  <p style="margin-bottom: 1rem;">The most popular and most spectacular pancake custom is the annual Pancake Race at Olney, Buckinghamshire, which is said to have been held since 1450. At the starting line each woman holds a frying pan containing a sizzling pancake. These rules are strictly kept: 1. Competitors must be eighteen or more in age and they must have lived in Olney Parish or Warrington for at least six months prior to the race; 2. Each woman must wear an apron and cover her head with a hat or scarf; 3. Loose-fitting trousers are barred; 4. All competitors must toss their pancakes at least three times during the race, once at the start, once during the final spurt to the church path and once at an optional point during the race.</p>
  <p style="margin-bottom: 1rem;">The first to serve her pancake to the bell ringer at the church door receives from him a traditional kiss and is hailed as the year's Pancake Champion.</p>
  <p style="margin-bottom: 1rem;">If the Other Club is a way for a few political elite to enjoy their aristocratic taste of leisure, then the practice of the Pancake Race is purely a folk custom. Although they are different both in form and participants, both of them throw some light on the traditional culture of Britain.</p>`
};

generateUnit(u);
