import os
import sys
import re
import json
import asyncio
from audio_lecture_engine import process_lecture_audio, update_supabase_page

LECTURE_CODE = '4_2'
LECTURE_ID = 'f45dd9b1-ef60-4521-a067-04bd896fc7e2'
COURSE_TITLE = 'IGCSE Geography (0460)'
LECTURE_TITLE = '4.2 Processes and Features Associated with Earthquakes and Volcanoes'

SEGMENTS = [
    {
        "id": "intro",
        "title": "Giới thiệu Bài 4.2: Cơ chế & Đặc điểm Động đất và Núi lửa",
        "selector": "#sec-header",
        "en": "Lesson 4.2: Processes and Features Associated with Earthquakes and Volcanoes. In this lesson, we explore seismic rupture mechanics, wave physics, focal depths, volcanic morphology, and primary eruptive phenomena.",
        "vi": "Bài bốn chấm hai: Các quá trình và Đặc điểm gắn liền với Động đất và Núi lửa. Trong bài học này, chúng ta sẽ tìm hiểu cơ chế đứt gãy địa chấn, vật lý sóng địa chấn, độ sâu chấn tiêu, hình thái núi lửa và các hiện tượng phun trào sơ cấp."
    },
    {
        "id": "sec_earthquake_processes",
        "title": "1. Cơ chế phát sinh động đất (Seismic Rupture)",
        "selector": "#sec-earthquake-processes",
        "en": "Section 1: How Earthquakes Occur. Frictional locking along geological faults accumulates immense elastic strain energy. When rock strength is exceeded, the fault abruptly ruptures, radiating energy outward in all directions.",
        "vi": "Phần một: Cơ chế phát sinh động đất. Ma sát dọc theo các đường đứt gãy địa chất tích lũy năng lượng biến dạng đàn hồi khổng lồ. Khi vượt quá sức chịu tải của đất đá, đứt gãy sẽ gãy vỡ đột ngột, giải phóng năng lượng bức xạ ra mọi hướng."
    },
    {
        "id": "seismic_focus",
        "title": "Chấn tiêu (Focus / Hypocentre) & Độ sâu chấn tiêu",
        "selector": "#seismic-focus",
        "en": "The Focus or Hypocentre. The exact subterranean rupture point within the lithosphere where rocks fracture and seismic waves originate. Shallow-focus earthquakes under seventy kilometres depth produce the most catastrophic surface violence.",
        "vi": "Chấn tiêu hay Điểm phát chấn. Điểm gãy vỡ ngầm chính xác trong lòng thạch quyển nơi đất đá bị đứt gãy và sóng địa chấn bắt đầu lan truyền. Các trận động đất có chấn tiêu nông dưới bảy mươi ki-lô-mét tạo ra sức tàn phá bề mặt khủng khiếp nhất."
    },
    {
        "id": "seismic_epicentre",
        "title": "Chấn tâm (Epicentre: Điểm trên mặt đất)",
        "selector": "#seismic-epicentre",
        "en": "The Epicentre. The point on the Earth's surface directly vertically above the focus. It lies closest to the subterranean rupture and typically suffers the highest peak ground acceleration and severe structural collapse.",
        "vi": "Chấn tâm. Điểm trên bề mặt Trái Đất nằm thẳng đứng ngay phía trên chấn tiêu. Đây là vị trí địa lý gần nguồn gãy vỡ ngầm nhất và thường phải hứng chịu gia tốc rung lắc mạnh nhất cùng sự sụp đổ nghiêm trọng của các công trình."
    },
    {
        "id": "seismic_waves",
        "title": "Các loại sóng địa chấn: Sóng P, Sóng S & Sóng mặt L",
        "selector": "#seismic-waves",
        "en": "Seismic Wave Types. Primary P-waves are fastest compressional waves travelling through solids and liquids. Secondary S-waves are slower shear waves travelling only through solids. Surface L-waves cause the greatest ground displacement and destruction.",
        "vi": "Các loại sóng địa chấn. Sóng dọc P là sóng nén nhanh nhất truyền được qua cả chất rắn và lỏng. Sóng ngang S chậm hơn chỉ truyền qua chất rắn. Sóng mặt L có tốc độ chậm nhất nhưng gây ra sự dịch chuyển mặt đất và sức tàn phá lớn nhất."
    },
    {
        "id": "sec_volcano_formation",
        "title": "2. Cơ chế hình thành và Phun trào Núi lửa",
        "selector": "#sec-volcano-formation",
        "en": "Section 2: How Volcanoes Form and Erupt. Magma generated by mantle decompression or subduction rises buoyantly through lithospheric fractures. As it ascends, decreasing pressure triggers explosive dissolved gas expansion.",
        "vi": "Phần hai: Cơ chế hình thành và Phun trào núi lửa. Magma sinh ra do giảm áp manti hoặc hút chìm nhẹ hơn sẽ trồi lên qua các khe nứt thạch quyển. Khi dâng lên, áp suất giảm kích hoạt sự bùng nổ dữ dội của các chất khí hòa tan."
    },
    {
        "id": "volc_magma_chamber",
        "title": "Túi magma & Ống dẫn chính (Magma Chamber & Conduit)",
        "selector": "#volc-magma-chamber",
        "en": "The Magma Chamber and Central Conduit. A subterranean reservoir where molten rock, steam, and sulfurous gases accumulate under high pressure before being blasted up the main cylindrical volcanic pipe.",
        "vi": "Túi magma và Ống dẫn trung tâm. Bể chứa ngầm sâu trong lòng đất nơi đá nóng chảy, hơi nước và khí lưu huỳnh tích tụ dưới áp suất cực lớn trước khi bị đẩy vọt lên qua ống dẫn núi lửa hình trụ chính."
    },
    {
        "id": "volc_pyroclastic",
        "title": "Dòng mạt vụn núi lửa (Pyroclastic Flow / Nuée Ardente)",
        "selector": "#volc-pyroclastic",
        "en": "Pyroclastic Flows. Superheated avalanches of gas, ash, and incandescent rock fragments racing down volcanic slopes at speeds exceeding two hundred kilometres per hour, incinerating everything at temperatures up to eight hundred degrees Celsius.",
        "vi": "Dòng mạt vụn núi lửa. Những dòng thác khí nóng bỏng, tro bụi và mảnh đá vụn nóng sáng lao xuống sườn núi với vận tốc vượt quá hai trăm ki-lô-mét một giờ, thiêu rụi mọi thứ trên đường đi ở nhiệt độ lên tới tám trăm độ C."
    },
    {
        "id": "volc_lahar",
        "title": "Dòng bùn núi lửa (Lahar: Thảm họa thung lũng)",
        "selector": "#volc-lahar",
        "en": "Lahars or Volcanic Mudflows. Torrents of volcanic ash, pulverized debris, boulders, and water surging down river valleys at highway speeds, triggered when eruptions melt summit ice caps or heavy monsoonal rain mobilizes loose tephra.",
        "vi": "Dòng bùn núi lửa. Dòng lũ bùn đất đá, tro bụi và nước cuồn cuộn chảy xuống các thung lũng sông với tốc độ chóng mặt, kích hoạt khi núi lửa phun làm tan băng tuyết trên đỉnh hoặc khi mưa bão cuốn trôi tro vụn chưa cố định."
    },
    {
        "id": "sec_volcano_types",
        "title": "3. Ba kiểu núi lửa cơ bản (Shield, Stratovolcano, Cinder)",
        "selector": "#sec-volcano-types",
        "en": "Section 3: Types of Volcanoes. Volcanic morphology depends on lava viscosity and gas pressure: effusive shield volcanoes, explosive composite stratovolcanoes, and steep symmetrical cinder cones.",
        "vi": "Phần ba: Ba kiểu núi lửa cơ bản. Hình thái núi lửa phụ thuộc vào độ nhớt của dung nham và áp suất khí: núi lửa hình khiên êm đềm, núi lửa tầng phun nổ dữ dội và nón xỉ dốc đối xứng."
    },
    {
        "id": "type_shield",
        "title": "Núi lửa hình khiên (Shield Volcano: Hawaii)",
        "selector": "#card-type-shield",
        "en": "Shield Volcanoes. Broad bases with gentle slopes under ten degrees formed of fluid basaltic lava that flows great distances before solidifying, producing gentle effusive lava fountains like Mauna Loa in Hawaii.",
        "vi": "Núi lửa hình khiên. Chân núi rất rộng với sườn thoải dưới mười độ được hình thành từ dung nham bazan lỏng chảy xa trước khi đông kết, tạo ra các vòi phun dung nham êm đềm như núi lửa Mauna Loa ở Ha-oai."
    },
    {
        "id": "type_stratovolcano",
        "title": "Núi lửa tầng / Nón hỗn hợp (Stratovolcano: Phú Sĩ, St. Helens)",
        "selector": "#card-type-stratovolcano",
        "en": "Stratovolcanoes or Composite Cones. Tall, steep symmetrical peaks constructed of alternating strata of viscous andesitic lava and pyroclastic tephra ash. Trapped gases generate catastrophic explosive eruptions like Mount Fuji and Mount St Helens.",
        "vi": "Núi lửa tầng hay Nón hỗn hợp. Đỉnh núi cao dốc hình nón đối xứng được tạo nên từ các lớp xen kẽ giữa dung nham quánh dẻo và tro bụi mạt vụn. Khí bị nghẽn tạo ra những vụ nổ kinh hoàng như núi Phú Sĩ và núi St Helens."
    },
    {
        "id": "type_cinder_cone",
        "title": "Nón xỉ / Nón tro (Cinder Cone: Parícutin)",
        "selector": "#card-type-cinder-cone",
        "en": "Cinder Cones. Small steep-sided cones typically under four hundred metres high, built from loose volcanic scoria and cinders ejected from a single vent, such as Parícutin in Mexico.",
        "vi": "Nón xỉ hay Nón tro. Những ngọn núi lửa nhỏ sườn dốc thường dưới bốn trăm mét, cấu tạo từ các mảnh xỉ và tro vụn xốp phun ra từ một miệng duy nhất, tiêu biểu như núi Parícutin ở Mê-hi-cô."
    },
    {
        "id": "sec_other_features",
        "title": "4. Các sản phẩm núi lửa khác & Địa hình kiến tạo",
        "selector": "#sec-other-features",
        "en": "Section 4: Other Volcanic Products and Tectonic Landforms. Enormous explosive collapses create summit calderas, advancing fissure lava flows engulf towns, and geothermal hot springs power sustainable energy.",
        "vi": "Phần bốn: Các sản phẩm núi lửa khác và Dạng địa hình kiến tạo. Những vụ nổ sụp đổ tạo ra các hõm chảo núi lửa khổng lồ, các dòng dung nham khe nứt tràn lấp làng mạc, và các nguồn nước nóng địa nhiệt cung cấp năng lượng sạch."
    },
    {
        "id": "feat_caldera_geothermal",
        "title": "Hõm chảo Caldera & Năng lượng địa nhiệt",
        "selector": "#card-caldera-geothermal",
        "en": "Calderas and Geothermal Energy. Enormous depressions formed when emptied magma chambers collapse inward under their own weight. Subterranean magma chambers also heat groundwater into geysers, harnessed extensively for clean geothermal energy in Iceland.",
        "vi": "Hõm chảo núi lửa và Năng lượng địa nhiệt. Những lòng chảo khổng lồ hình thành khi túi magma rỗng bị sụp đổ dưới trọng lượng của chính nó. Magma ngầm cũng đun nóng nước ngầm tạo thành các mạch nước phun, được khai thác phục vụ năng lượng địa nhiệt sạch tại Băng Đảo."
    }
]

MAJOR_SECTIONS = {
    "intro": {"start": 0, "end": 4},
    "sec_earthquake_processes": {"start": 1, "end": 4},
    "sec_volcano_formation": {"start": 5, "end": 8},
    "sec_volcano_types": {"start": 9, "end": 12},
    "sec_other_features": {"start": 13, "end": 14}
}

def transform_html(raw_html):
    html = raw_html
    
    # 1. Header
    html = re.sub(
        r'(<div style="background:linear-gradient\(135deg, #b91c1c, #dc2626, #ea580c\);[^"]*">[\s\S]*?</div>)',
        r'<div id="sec-header" class="lecture-interactive-card" data-lecture-section="intro" style="cursor:pointer; border-radius:12px; margin-bottom:24px; transition:all 0.2s ease;">\1</div>',
        html, count=1
    )
    
    # 2. Section 1: Seismic Processes
    html = re.sub(
        r'(<h2 style="color:#b91c1c;[^"]*">\s*1\. How Earthquakes Occur \(Seismic Processes\)\s*</h2>)',
        r'<div id="sec-earthquake-processes" class="lecture-interactive-card" data-lecture-section="sec_earthquake_processes" style="cursor:pointer; border-radius:12px; padding:12px; margin-top:28px; transition:all 0.2s ease;">\1',
        html, count=1
    )
    # close before Section 2
    html = re.sub(
        r'(\s*)(<h2 style="color:#b91c1c;[^"]*">\s*2\. How Volcanoes Form)',
        r'</div>\1\2',
        html, count=1
    )
    
    # SVG 1 nodes
    html = html.replace('<rect x="70" y="270" width="135" height="42" rx="5" fill="#0f172a" stroke="#fbbf24" stroke-width="1"/>', '<g id="seismic-focus" data-lecture-section="seismic_focus" style="cursor:pointer;"><rect x="70" y="270" width="135" height="42" rx="5" fill="#0f172a" stroke="#fbbf24" stroke-width="1"/>')
    html = html.replace('<text x="137" y="302" fill="#cbd5e1" font-size="9.5" text-anchor="middle">Point where rock fractures</text>', '<text x="137" y="302" fill="#cbd5e1" font-size="9.5" text-anchor="middle">Point where rock fractures</text></g>')
    
    html = html.replace('<rect x="485" y="45" width="160" height="50" rx="5" fill="#0f172a" stroke="#ef4444" stroke-width="1"/>', '<g id="seismic-epicentre" data-lecture-section="seismic_epicentre" style="cursor:pointer;"><rect x="485" y="45" width="160" height="50" rx="5" fill="#0f172a" stroke="#ef4444" stroke-width="1"/>')
    html = html.replace('<text x="565" y="91" fill="#fca5a5" font-size="9" text-anchor="middle">Experiences strongest shaking</text>', '<text x="565" y="91" fill="#fca5a5" font-size="9" text-anchor="middle">Experiences strongest shaking</text></g>')
    
    html = html.replace('<rect x="640" y="240" width="190" height="150" rx="6" fill="#0f172a" stroke="#334155"/>', '<g id="seismic-waves" data-lecture-section="seismic_waves" style="cursor:pointer;"><rect x="640" y="240" width="190" height="150" rx="6" fill="#0f172a" stroke="#334155"/>')
    html = html.replace('<text x="665" y="383" fill="#94a3b8" font-size="10">Slowest, causes most destruction.</text>', '<text x="665" y="383" fill="#94a3b8" font-size="10">Slowest, causes most destruction.</text></g>')
    
    # 3. Section 2: Volcano Formation
    html = re.sub(
        r'(<h2 style="color:#b91c1c;[^"]*">\s*2\. How Volcanoes Form and Erupt\s*</h2>)',
        r'<div id="sec-volcano-formation" class="lecture-interactive-card" data-lecture-section="sec_volcano_formation" style="cursor:pointer; border-radius:12px; padding:12px; margin-top:28px; transition:all 0.2s ease;">\1',
        html, count=1
    )
    # close before Section 3
    html = re.sub(
        r'(\s*)(<h2 style="color:#b91c1c;[^"]*">\s*3\. Types of Volcanoes)',
        r'</div>\1\2',
        html, count=1
    )
    
    # SVG 2 volcano elements
    html = html.replace('<ellipse cx="420" cy="380" rx="130" ry="50" fill="url(#magmaChamberGrad)" stroke="#b91c1c" stroke-width="2"/>', '<g id="volc-magma-chamber" data-lecture-section="volc_magma_chamber" style="cursor:pointer;"><ellipse cx="420" cy="380" rx="130" ry="50" fill="url(#magmaChamberGrad)" stroke="#b91c1c" stroke-width="2"/>')
    html = html.replace('<text x="420" y="402" fill="#fef08a" font-size="10.5" text-anchor="middle">High gas pressure &amp; viscous andesitic magma</text>', '<text x="420" y="402" fill="#fef08a" font-size="10.5" text-anchor="middle">High gas pressure &amp; viscous andesitic magma</text></g>')
    
    html = html.replace('<text x="80" y="240" fill="#b91c1c" font-size="12" font-weight="bold">🔥 Pyroclastic Flow</text>', '<g id="volc-pyroclastic" data-lecture-section="volc_pyroclastic" style="cursor:pointer;"><text x="80" y="240" fill="#b91c1c" font-size="12" font-weight="bold">🔥 Pyroclastic Flow</text>')
    html = html.replace('<text x="80" y="255" fill="#475569" font-size="10">(Nuée ardente, &gt;700°C, 200 km/h)</text>', '<text x="80" y="255" fill="#475569" font-size="10">(Nuée ardente, &gt;700°C, 200 km/h)</text></g>')
    
    html = html.replace('<rect x="40" y="325" width="90" height="20" rx="4" fill="#a8a29e"/>', '<g id="volc-lahar" data-lecture-section="volc_lahar" style="cursor:pointer;"><rect x="40" y="325" width="90" height="20" rx="4" fill="#a8a29e"/>')
    html = html.replace('<text x="85" y="340" fill="#1e293b" font-size="11" font-weight="bold" text-anchor="middle">Lahar (Mudflow)</text>', '<text x="85" y="340" fill="#1e293b" font-size="11" font-weight="bold" text-anchor="middle">Lahar (Mudflow)</text></g>')
    
    # 4. Section 3: Volcano Types
    html = re.sub(
        r'(<h2 style="color:#b91c1c;[^"]*">\s*3\. Types of Volcanoes\s*</h2>)',
        r'<div id="sec-volcano-types" class="lecture-interactive-card" data-lecture-section="sec_volcano_types" style="cursor:pointer; border-radius:12px; padding:12px; margin-top:28px; transition:all 0.2s ease;">\1',
        html, count=1
    )
    # close before Section 4
    html = re.sub(
        r'(\s*)(<h2 style="color:#b91c1c;[^"]*">\s*4\. Other Volcanic Products)',
        r'</div>\1\2',
        html, count=1
    )
    
    # Table rows in Volcano Types
    html = html.replace('<tr>\n            <td style="padding:10px 14px; border:1px solid #e2e8f0; font-weight:bold; color:#0369a1;">Shield Volcano</td>', '<tr id="card-type-shield" class="lecture-interactive-card" data-lecture-section="type_shield" style="cursor:pointer;">\n            <td style="padding:10px 14px; border:1px solid #e2e8f0; font-weight:bold; color:#0369a1;">Shield Volcano</td>')
    html = html.replace('<tr style="background:#f8fafc;">\n            <td style="padding:10px 14px; border:1px solid #e2e8f0; font-weight:bold; color:#dc2626;">Stratovolcano (Composite Cone)</td>', '<tr id="card-type-stratovolcano" class="lecture-interactive-card" data-lecture-section="type_stratovolcano" style="background:#f8fafc; cursor:pointer;">\n            <td style="padding:10px 14px; border:1px solid #e2e8f0; font-weight:bold; color:#dc2626;">Stratovolcano (Composite Cone)</td>')
    html = html.replace('<tr>\n            <td style="padding:10px 14px; border:1px solid #e2e8f0; font-weight:bold; color:#d97706;">Cinder Cone (Ash/Scoria Cone)</td>', '<tr id="card-type-cinder-cone" class="lecture-interactive-card" data-lecture-section="type_cinder_cone" style="cursor:pointer;">\n            <td style="padding:10px 14px; border:1px solid #e2e8f0; font-weight:bold; color:#d97706;">Cinder Cone (Ash/Scoria Cone)</td>')
    
    # 5. Section 4: Other Features
    html = re.sub(
        r'(<h2 style="color:#b91c1c;[^"]*">\s*4\. Other Volcanic Products and Tectonic Landforms\s*</h2>)',
        r'<div id="sec-other-features" class="lecture-interactive-card" data-lecture-section="sec_other_features" style="cursor:pointer; border-radius:12px; padding:12px; margin-top:28px; transition:all 0.2s ease;">\1',
        html, count=1
    )
    
    html = html.replace(
        '<div style="background:#fff7ed; border-left:4px solid #f97316; border-radius:8px; padding:18px 20px; margin:20px 0;">\n      <h3 style="margin-top:0; color:#c2410c; font-size:17px; font-weight:bold;">Major Eruptive Features &amp; Secondary Hazards</h3>',
        '<div id="card-caldera-geothermal" class="lecture-interactive-card" data-lecture-section="feat_caldera_geothermal" style="background:#fff7ed; border-left:4px solid #f97316; border-radius:8px; padding:18px 20px; margin:20px 0; cursor:pointer;">\n      <h3 style="margin-top:0; color:#c2410c; font-size:17px; font-weight:bold;">Major Eruptive Features &amp; Secondary Hazards</h3>'
    )
    
    html += '</div>'
    return html

async def main():
    manifest = await process_lecture_audio(
        LECTURE_CODE, LECTURE_ID, COURSE_TITLE, LECTURE_TITLE,
        SEGMENTS, MAJOR_SECTIONS
    )
    
    raw_path = f"scratch/lectures/{LECTURE_CODE}_p1.html"
    with open(raw_path, 'r', encoding='utf-8') as f:
        raw_html = f.read()
    
    new_html = transform_html(raw_html)
    
    interactive_path = f"scratch/lectures/{LECTURE_CODE}_p1_interactive.html"
    with open(interactive_path, 'w', encoding='utf-8') as f:
        f.write(new_html)
    print(f"Transformed HTML saved to {interactive_path}")
    
    update_supabase_page(LECTURE_ID, new_html)
    print(f"Lecture {LECTURE_CODE} fully processed and uploaded!")

if __name__ == '__main__':
    asyncio.run(main())
