import os
import sys
import re
import json
import asyncio
from audio_lecture_engine import process_lecture_audio, sb

if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

# Lecture 3.1 ID
LID = '6cbe4a84-26ed-4a1d-933b-5843e9b9a501'
CODE = '3_1'
TITLE = '3.1. Marketing, competition and the customer'
COURSE_TITLE = 'Cambridge IGCSE Business Studies'

# ==============================================================================
# 1. DEFINE ALL 12 AUDIO SEGMENTS FOR LESSON 3.1
# ==============================================================================
segments = [
    {
        "id": "intro",
        "title": "Giới thiệu Bài 3.1: Tiếp thị, Cạnh tranh và Khách hàng",
        "selector": "#sec-header",
        "en": "Welcome to Cambridge IGCSE Business Studies, Chapter 3.1: Marketing, Competition and the Customer. In this opening chapter of Topic 3, we define the strategic role of marketing, explore why consumer spending patterns change, evaluate intensifying market competition, contrast niche versus mass marketing, and analyze market segmentation.",
        "vi": "Chào mừng các bạn đến với môn Kinh doanh Cambridge IGCSE, Bài 3.1: Tiếp thị, Cạnh tranh và Khách hàng. Trong bài mở đầu của Chủ đề ba về Tiếp thị, chúng ta sẽ định nghĩa vai trò chiến lược của marketing, tìm hiểu lý do thay đổi xu hướng tiêu dùng, đánh giá áp lực cạnh tranh gia tăng, so sánh thị trường ngách với thị trường đại trà và phân tích phân đoạn thị trường."
    },
    {
        "id": "sec_what_is_marketing",
        "title": "1. Bản chất và Vai trò của Tiếp thị (Marketing)",
        "selector": "#sec-what-is-marketing",
        "en": "Section 1 defines marketing as the management process responsible for identifying, anticipating, and satisfying customer requirements profitably. Modern marketing builds long-term customer relationships and brand equity rather than merely pursuing one-off transactions.",
        "vi": "Mục một định nghĩa marketing là quá trình quản trị chịu trách nhiệm nhận diện, dự đoán và thỏa mãn các yêu cầu của khách hàng một cách có sinh lời. Marketing hiện đại tập trung vào việc nuôi dưỡng mối quan hệ khách hàng dài hạn và xây dựng giá trị thương hiệu bền vững thay vì chỉ theo đuổi các giao dịch đơn lẻ."
    },
    {
        "id": "card_marketing_role",
        "title": "🌟 Năm Vai trò Trọng tâm của Marketing",
        "selector": "#card-marketing-role",
        "en": "Marketing executes five critical functions: identifying customer needs through research; satisfying those needs with the right product design; maintaining brand loyalty through customer care; gaining competitive intelligence; and anticipating shifting future preferences before rivals.",
        "vi": "Marketing thực hiện năm chức năng trọng tâm: nhận diện nhu cầu khách hàng qua nghiên cứu thị trường; thỏa mãn nhu cầu bằng việc thiết kế sản phẩm chuẩn xác; duy trì lòng trung thành qua chế độ chăm sóc khách hàng; thu thập thông tin thị trường; và dự đoán các biến chuyển thị hiếu tương lai trước các đối thủ cạnh tranh."
    },
    {
        "id": "card_marketing_objectives",
        "title": "🎯 Mục tiêu Marketing & Công thức Tính Thị phần (Market Share)",
        "selector": "#card-marketing-objectives",
        "en": "Marketing objectives guide corporate efforts: increasing sales revenue, developing replacement products, and expanding market share. Market share represents the percentage of total industry sales generated by a specific company, calculated by dividing company sales by total market sales and multiplying by one hundred.",
        "vi": "Các mục tiêu marketing định hướng hoạt động doanh nghiệp: gia tăng doanh thu bán hàng, phát triển sản phẩm mới và mở rộng thị phần. Thị phần (Market share) là tỷ lệ phần trăm doanh số của doanh nghiệp chiếm trong tổng dung lượng thị trường, được tính bằng cách lấy doanh số của doanh nghiệp chia cho tổng doanh số toàn thị trường và nhân với 100."
    },
    {
        "id": "sec_market_changes",
        "title": "2. Biến động Thị trường và Áp lực Cạnh tranh",
        "selector": "#sec-market-changes",
        "en": "Section 2 investigates dynamic markets. Spending habits constantly shift due to changing trends, technological obsolescence, rising disposable incomes, and demographic aging. Concurrently, globalization, improved international transport, and e-commerce platforms intensify global competition.",
        "vi": "Mục hai nghiên cứu sự biến động của thị trường. Xu hướng chi tiêu liên tục thay đổi do thị hiếu thời trang mới, công nghệ đào thải các sản phẩm cũ, thu nhập khả dụng gia tăng và xu hướng già hóa dân số. Đồng thời, toàn cầu hóa, sự cải tiến vận tải quốc tế và các nền tảng thương mại điện tử làm bùng nổ áp lực cạnh tranh trên toàn cầu."
    },
    {
        "id": "card_spending_patterns",
        "title": "❓ Vì sao Mô hình Chi tiêu của Người tiêu dùng Thay đổi?",
        "selector": "#card-spending-patterns",
        "en": "Customer spending shifts in response to four forces: evolving tastes and fashion preferences; technological innovation rendering legacy items obsolete; fluctuations in household disposable income; and demographic shifts such as aging populations demanding specialized healthcare products.",
        "vi": "Mô hình chi tiêu của khách hàng biến động do bốn động lực chính: sự thay đổi thị hiếu và xu hướng thời trang; đổi mới công nghệ khiến các sản phẩm cũ bị lỗi thời; biến động thu nhập khả dụng của hộ gia đình; và các chuyển dịch nhân khẩu học như già hóa dân số làm tăng nhu cầu các sản phẩm chăm sóc sức khỏe chuyên biệt."
    },
    {
        "id": "card_competition_response",
        "title": "⚔️ Cạnh tranh Gia tăng và Chiến lược Ứng phó của Doanh nghiệp",
        "selector": "#card-competition-response",
        "en": "To withstand intense rivalry driven by globalization and digital commerce, businesses must respond strategically: nurturing close customer relationships to retain brand loyalty; continually refining existing products; launching innovative offerings; and maintaining tight cost control to sustain competitive pricing.",
        "vi": "Để trụ vững trước sự cạnh tranh khốc liệt từ toàn cầu hóa và thương mại điện tử, doanh nghiệp phải ứng phó bằng các chiến lược trọng tâm: nuôi dưỡng mối quan hệ chặt chẽ với khách hàng để giữ vững lòng trung thành; liên tục cải tiến chất lượng sản phẩm hiện có; ra mắt các dòng sản phẩm sáng tạo mới; và quản trị chi phí chặt chẽ để duy trì mức giá bán cạnh tranh."
    },
    {
        "id": "sec_niche_mass",
        "title": "3. Thị trường Ngách (Niche) và Thị trường Đại trà (Mass)",
        "selector": "#sec-niche-mass",
        "en": "Section 3 compares market scope strategies. Niche marketing targets small, specialized segments with tailored offerings, while mass marketing distributes standardized goods to the wider general public.",
        "vi": "Mục ba so sánh chiến lược quy mô thị trường. Thị trường ngách (Niche marketing) nhắm vào các phân khúc nhỏ với các sản phẩm chuyên biệt độc đáo, trong khi thị trường đại trà (Mass marketing) phân phối các sản phẩm chuẩn hóa tới đông đảo công chúng trên diện rộng."
    },
    {
        "id": "card_niche_marketing",
        "title": "💎 Thị trường Ngách (Niche Marketing): Ưu và Nhược điểm",
        "selector": "#card-niche-marketing",
        "en": "Niche marketing enables smaller businesses to avoid direct confrontation with multinational giants, cater precisely to specialized tastes, and command premium price margins. However, it lacks economies of scale, caps maximum revenue potential, and leaves the firm vulnerable if consumer niche demand collapses.",
        "vi": "Thị trường ngách cho phép các doanh nghiệp vừa và nhỏ tránh đối đầu trực diện với các tập đoàn đa quốc gia khổng lồ, phục vụ sát sao nhu cầu đặc thù và áp đặt mức giá bán cao với biên lợi nhuận lớn. Tuy nhiên, thị trường ngách thiếu tính kinh tế theo quy mô, giới hạn doanh thu tối đa và dễ rơi vào thế hiểm nghèo nếu nhu cầu phân khúc đó sụt giảm."
    },
    {
        "id": "card_mass_marketing",
        "title": "🌎 Thị trường Đại trà (Mass Marketing): Ưu và Nhược điểm",
        "selector": "#card-mass-marketing",
        "en": "Mass marketing achieves massive aggregate sales volumes, exploits extensive production economies of scale to slash average unit costs, and diversifies commercial risks across broad audiences. Its drawbacks include ferocious price competition, costly mass-media marketing budgets, and inability to meet distinct consumer preferences.",
        "vi": "Thị trường đại trà mang lại sản lượng tiêu thụ khổng lồ, khai thác triệt để tính kinh tế của quy mô để kéo giảm chi phí sản xuất bình quân trên mỗi đơn vị và phân tán rủi ro trên diện rộng. Nhược điểm lớn là cạnh tranh giá khốc liệt từ các đối thủ lớn, chi phí quảng cáo truyền thông tốn kém và không đáp ứng được sở thích riêng biệt của từng nhóm khách hàng."
    },
    {
        "id": "sec_segmentation",
        "title": "🧩 4. Phân đoạn Thị trường (Market Segmentation)",
        "selector": "#sec-segmentation",
        "en": "Section 4 examines market segmentation—dividing a broad consumer base into identifiable subgroups sharing common characteristics. Segmentation criteria include socio-economic income brackets, demographic age groups, geographic regions, and gender profiles, enabling targeted four-P marketing mixes.",
        "vi": "Mục bốn phân tích phân đoạn thị trường – việc phân chia thị trường tổng thể thành các nhóm nhỏ có chung các đặc tính tiêu dùng tương đồng. Các tiêu chí phân đoạn bao gồm mức thu nhập kinh tế xã hội, nhóm tuổi nhân khẩu học, vị trí địa lý vùng miền và giới tính, từ đó giúp doanh nghiệp thiết kế chiến lược 4P chính xác cho từng đối tượng."
    },
    {
        "id": "sec_recommend_segmentation",
        "title": "🎯 5. Chiến lược làm bài thi Cambridge: Đề xuất Phân đoạn Thị trường",
        "selector": "#sec-recommend-segmentation",
        "en": "Section 5 details Cambridge exam technique for segmentation scenarios. Candidates must recommend the most suitable segmentation method for the case study business, justify how it optimizes advertising expenditure, avoids marketing waste, and supports appropriate pricing strategies.",
        "vi": "Mục năm cung cấp kỹ năng làm bài thi Cambridge cho các câu hỏi tình huống phân đoạn thị trường. Thí sinh phải đề xuất tiêu chí phân khúc tối ưu cho doanh nghiệp trong đề bài, lập luận cách thức phân khúc giúp tối ưu hóa ngân sách quảng cáo, tránh lãng phí chi phí tiếp thị và hỗ trợ chiến lược định giá phù hợp."
    }
]

major_sections = {
    "intro": {"start": 0, "end": 0},
    "sec_what_is_marketing": {"start": 1, "end": 3},
    "sec_market_changes": {"start": 4, "end": 6},
    "sec_niche_mass": {"start": 7, "end": 9},
    "sec_segmentation": {"start": 10, "end": 10},
    "sec_recommend_segmentation": {"start": 11, "end": 11}
}

# ==============================================================================
# 2. GENERATE NEW HTML FOR PAGE 1
# ==============================================================================
def build_page_1_html():
    html = """<div style="font-family: 'Segoe UI', Arial, sans-serif; width: 100%; margin: 20px auto; color: #334155; line-height: 1.6; box-sizing: border-box;">

    <!-- TOP HEADER BANNER (NO STUDY RESOURCES) -->
    <div id="sec-header" class="lecture-interactive-card" data-lecture-section="intro" style="margin-bottom: 35px; padding: 22px 26px; background: linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%); border-radius: 14px; border: 1px solid #e2e8f0; cursor: pointer; transition: all 0.2s; box-shadow: 0 2px 6px rgba(0,0,0,0.02);">
        <div style="display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 12px;">
            <div>
                <span style="font-size: 12px; font-weight: 700; color: #0284c7; text-transform: uppercase; letter-spacing: 0.8px;">Cambridge IGCSE Business Studies (0450) • Unit 3</span>
                <h1 style="margin: 4px 0 0 0; font-size: 26px; color: #0f172a; font-weight: 800; line-height: 1.2;">3.1 Marketing, Competition and the Customer (Tiếp thị, Cạnh tranh &amp; Khách hàng)</h1>
            </div>
            <div style="font-size: 13px; color: #475569; background: #ffffff; padding: 7px 16px; border-radius: 20px; border: 1px solid #cbd5e1; font-weight: 600; display: flex; align-items: center; gap: 6px;">
                <span>🎙️</span> Bấm vào thẻ để nghe giảng chi tiết
            </div>
        </div>
    </div>

    <!-- 1. WHAT IS MARKETING? -->
    <div style="margin-bottom: 45px;">
        <div id="sec-what-is-marketing" class="lecture-interactive-card" data-lecture-section="sec_what_is_marketing" style="margin-bottom: 20px; padding: 22px 24px; background: #ffffff; border: 1px solid #e2e8f0; border-radius: 14px; box-shadow: 0 2px 8px rgba(0,0,0,0.02); cursor: pointer; transition: all 0.2s;">
            <h2 style="color: #0f172a; border-bottom: 3px solid #3b82f6; padding-bottom: 12px; margin-bottom: 14px; display: inline-block; font-size: 24px; line-height: 1.2; margin-top: 0;">🎯 1. WHAT IS MARKETING?</h2>
            <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 14px;">
                <div style="background: #f8fafc; border: 1px solid #cbd5e1; border-radius: 8px; padding: 16px;">
                    <b style="color: #0f172a; font-size: 16px;">🛒 Market:</b>
                    <p style="margin: 5px 0 0 0; font-size: 14px; color: #475569;">Consists of all current and potential buyers and sellers of a particular good or service.</p>
                </div>
                <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 8px; padding: 16px;">
                    <b style="color: #1d4ed8; font-size: 16px;">📢 Marketing:</b>
                    <p style="margin: 5px 0 0 0; font-size: 14px; color: #1e40af;">The management process responsible for <b>identifying, anticipating and satisfying consumer requirements profitably</b>.</p>
                </div>
            </div>
        </div>

        <div id="card-marketing-role" class="lecture-interactive-card" data-lecture-section="card_marketing_role" style="background: #ffffff; border: 1.5px solid #cbd5e1; border-radius: 12px; padding: 22px; margin-bottom: 20px; cursor: pointer; transition: all 0.2s; box-shadow: 0 2px 6px rgba(0,0,0,0.02);">
            <h3 style="color: #0f172a; font-size: 18px; margin-top: 0; margin-bottom: 14px;">🌟 5 Core Roles of Marketing</h3>
            <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 12px;">
                <div style="background: #f8fafc; border-left: 4px solid #3b82f6; padding: 12px 14px; border-radius: 6px; border: 1px solid #e2e8f0;">
                    <b style="color: #2563eb; font-size: 14px;">1. Identifying needs:</b>
                    <p style="margin: 4px 0 0 0; font-size: 13px; color: #475569;">Carrying out research to uncover customer desires.</p>
                </div>
                <div style="background: #f8fafc; border-left: 4px solid #3b82f6; padding: 12px 14px; border-radius: 6px; border: 1px solid #e2e8f0;">
                    <b style="color: #2563eb; font-size: 14px;">2. Satisfying needs:</b>
                    <p style="margin: 4px 0 0 0; font-size: 13px; color: #475569;">Developing, branding, and selling the right products.</p>
                </div>
                <div style="background: #f8fafc; border-left: 4px solid #3b82f6; padding: 12px 14px; border-radius: 6px; border: 1px solid #e2e8f0;">
                    <b style="color: #2563eb; font-size: 14px;">3. Building loyalty:</b>
                    <p style="margin: 4px 0 0 0; font-size: 13px; color: #475569;">Rewarding customer retention and delivering quality service.</p>
                </div>
                <div style="background: #f8fafc; border-left: 4px solid #3b82f6; padding: 12px 14px; border-radius: 6px; border: 1px solid #e2e8f0;">
                    <b style="color: #2563eb; font-size: 14px;">4. Market intelligence:</b>
                    <p style="margin: 4px 0 0 0; font-size: 13px; color: #475569;">Analyzing competitors and buyer behavior patterns.</p>
                </div>
                <div style="background: #f8fafc; border-left: 4px solid #3b82f6; padding: 12px 14px; border-radius: 6px; border: 1px solid #e2e8f0;">
                    <b style="color: #2563eb; font-size: 14px;">5. Anticipating changes:</b>
                    <p style="margin: 4px 0 0 0; font-size: 13px; color: #475569;">Forecasting future trends to innovate before rivals.</p>
                </div>
            </div>
        </div>

        <div id="card-marketing-objectives" class="lecture-interactive-card" data-lecture-section="card_marketing_objectives" style="background: #ffffff; border: 1.5px solid #cbd5e1; border-radius: 12px; padding: 22px; cursor: pointer; transition: all 0.2s; box-shadow: 0 2px 6px rgba(0,0,0,0.02);">
            <h3 style="color: #0f172a; font-size: 18px; margin-top: 0; margin-bottom: 12px;">🎯 Marketing Objectives &amp; Market Share Formula</h3>
            <p style="font-size: 14px; color: #475569; margin-bottom: 12px;">Objectives include raising brand awareness, increasing sales revenue, and expanding market share:</p>
            <div style="background: #fdf4ff; border: 1.5px solid #e9d5ff; border-radius: 10px; padding: 16px;">
                <b style="color: #7e22ce; font-size: 15px;">🧮 Calculating Market Share:</b>
                <div style="font-size: 14px; color: #581c87; margin: 8px 0; font-weight: bold; background: #ffffff; padding: 10px 14px; border-radius: 6px; display: inline-block; border: 1px solid #ddd6fe;">
                    Market Share (%) = (Company Sales / Total Market Sales) × 100
                </div>
                <p style="margin: 6px 0 0 0; font-size: 13px; color: #6b21a8;">
                    <i>Example: If industry toy sales equal $1,000,000 and Firm A generates $300,000, Firm A's market share is 30%.</i>
                </p>
            </div>
        </div>
    </div>

    <!-- 2. MARKET CHANGES -->
    <div style="margin-bottom: 45px;">
        <div id="sec-market-changes" class="lecture-interactive-card" data-lecture-section="sec_market_changes" style="margin-bottom: 20px; padding: 22px 24px; background: #ffffff; border: 1px solid #e2e8f0; border-radius: 14px; box-shadow: 0 2px 8px rgba(0,0,0,0.02); cursor: pointer; transition: all 0.2s;">
            <h2 style="color: #0f172a; border-bottom: 3px solid #f97316; padding-bottom: 12px; margin-bottom: 14px; display: inline-block; font-size: 24px; line-height: 1.2; margin-top: 0;">📈 2. MARKET CHANGES &amp; COMPETITION</h2>
            <p style="font-size: 15px; color: #475569; margin: 0; line-height: 1.6;">
                Markets are dynamic environments where consumer spending patterns evolve rapidly and competitive forces intensify.
            </p>
        </div>

        <div id="card-spending-patterns" class="lecture-interactive-card" data-lecture-section="card_spending_patterns" style="background: #ffffff; border: 1.5px solid #cbd5e1; border-radius: 12px; padding: 22px; margin-bottom: 20px; cursor: pointer; transition: all 0.2s; box-shadow: 0 2px 6px rgba(0,0,0,0.02);">
            <h3 style="color: #c2410c; font-size: 18px; margin-top: 0; margin-bottom: 12px;">❓ Why Consumer Spending Patterns Change</h3>
            <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 12px;">
                <div style="background: #fff7ed; border: 1px solid #fed7aa; padding: 12px; border-radius: 8px;">
                    <b style="color: #c2410c; font-size: 14px;">👗 Tastes &amp; Fashion:</b>
                    <p style="margin: 4px 0 0 0; font-size: 13px; color: #475569;">Social media and cultural trends rapidly alter lifestyle preferences.</p>
                </div>
                <div style="background: #fff7ed; border: 1px solid #fed7aa; padding: 12px; border-radius: 8px;">
                    <b style="color: #c2410c; font-size: 14px;">💻 Technology:</b>
                    <p style="margin: 4px 0 0 0; font-size: 13px; color: #475569;">Smart digital innovations render physical legacy products obsolete.</p>
                </div>
                <div style="background: #fff7ed; border: 1px solid #fed7aa; padding: 12px; border-radius: 8px;">
                    <b style="color: #c2410c; font-size: 14px;">💵 Incomes:</b>
                    <p style="margin: 4px 0 0 0; font-size: 13px; color: #475569;">Economic growth boosts luxury sales; recessions spur discount demand.</p>
                </div>
                <div style="background: #fff7ed; border: 1px solid #fed7aa; padding: 12px; border-radius: 8px;">
                    <b style="color: #c2410c; font-size: 14px;">👴 Ageing Demographics:</b>
                    <p style="margin: 4px 0 0 0; font-size: 13px; color: #475569;">Older populations increase healthcare, retirement, and travel demand.</p>
                </div>
            </div>
        </div>

        <div id="card-competition-response" class="lecture-interactive-card" data-lecture-section="card_competition_response" style="background: #ffffff; border: 1.5px solid #cbd5e1; border-radius: 12px; padding: 22px; cursor: pointer; transition: all 0.2s; box-shadow: 0 2px 6px rgba(0,0,0,0.02);">
            <h3 style="color: #0f172a; font-size: 18px; margin-top: 0; margin-bottom: 12px;">⚔️ Why Competition Increased &amp; How Businesses Respond</h3>
            <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 14px;">
                <div style="background: #f8fafc; border: 1px solid #cbd5e1; border-radius: 8px; padding: 16px;">
                    <b style="color: #0f172a; font-size: 15px;">🌐 Causes of Intensified Rivalry:</b>
                    <ul style="margin: 6px 0 0 0; padding-left: 18px; font-size: 13px; color: #475569; line-height: 1.5;">
                        <li><b>Globalization:</b> Multinational brands compete in local domestic markets.</li>
                        <li><b>Transport advances:</b> Efficient air/sea logistics lower freight barriers.</li>
                        <li><b>E-Commerce:</b> Online platforms enable consumers to compare prices worldwide.</li>
                    </ul>
                </div>
                <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 16px;">
                    <b style="color: #15803d; font-size: 15px;">🛠️ Strategic Business Responses:</b>
                    <ul style="margin: 6px 0 0 0; padding-left: 18px; font-size: 13px; color: #166534; line-height: 1.5;">
                        <li><b>Customer loyalty programmes:</b> Maintain retention and repeat purchases.</li>
                        <li><b>Continuous R&amp;D innovation:</b> Launch refreshed products to outpace rivals.</li>
                        <li><b>Strict cost management:</b> Lower unit costs to offer competitive consumer prices.</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <!-- 3. NICHE & MASS MARKETING -->
    <div style="margin-bottom: 45px;">
        <div id="sec-niche-mass" class="lecture-interactive-card" data-lecture-section="sec_niche_mass" style="margin-bottom: 20px; padding: 22px 24px; background: #ffffff; border: 1px solid #e2e8f0; border-radius: 14px; box-shadow: 0 2px 8px rgba(0,0,0,0.02); cursor: pointer; transition: all 0.2s;">
            <h2 style="color: #0f172a; border-bottom: 3px solid #8b5cf6; padding-bottom: 12px; margin-bottom: 14px; display: inline-block; font-size: 24px; line-height: 1.2; margin-top: 0;">⚖️ 3. NICHE &amp; MASS MARKETING</h2>
            <p style="font-size: 15px; color: #475569; margin: 0; line-height: 1.6;">
                Enterprises choose between targeting a highly focused specialized segment or distributing to the mass marketplace:
            </p>
        </div>

        <div id="card-niche-marketing" class="lecture-interactive-card" data-lecture-section="card_niche_marketing" style="background: #ffffff; border: 1.5px solid #cbd5e1; border-radius: 12px; padding: 22px; margin-bottom: 20px; cursor: pointer; transition: all 0.2s; box-shadow: 0 2px 6px rgba(0,0,0,0.02);">
            <div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 10px;">
                <h3 style="color: #6d28d9; font-size: 18px; margin: 0;">💎 Niche Marketing (Specialized Segment)</h3>
                <span style="background: #f5f3ff; color: #6d28d9; padding: 4px 10px; border-radius: 6px; font-size: 12px; font-weight: bold;">High Margin</span>
            </div>
            <p style="font-size: 14px; color: #475569; margin: 0 0 12px 0;">Targeting a small segment of a larger market with specialized products (e.g. luxury sports cars, vegan bakery).</p>
            <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 12px;">
                <div style="background: #f0fdf4; border: 1px solid #bbf7d0; padding: 12px; border-radius: 8px;">
                    <b style="color: #15803d; font-size: 13.5px;">✅ Advantages:</b>
                    <ul style="margin: 4px 0 0 0; padding-left: 18px; font-size: 13px; color: #166534; line-height: 1.4;">
                        <li>Less competition from massive multinational corporations.</li>
                        <li>High pricing power leading to premium profit margins.</li>
                        <li>Intense customer loyalty from fulfilling exact needs.</li>
                    </ul>
                </div>
                <div style="background: #fef2f2; border: 1px solid #fecaca; padding: 12px; border-radius: 8px;">
                    <b style="color: #b91c1c; font-size: 13.5px;">❌ Disadvantages:</b>
                    <ul style="margin: 4px 0 0 0; padding-left: 18px; font-size: 13px; color: #991b1b; line-height: 1.4;">
                        <li>No economies of scale; higher average production costs.</li>
                        <li>Vulnerable to total collapse if consumer niche tastes change.</li>
                        <li>Limited market size restricts overall revenue ceilings.</li>
                    </ul>
                </div>
            </div>
        </div>

        <div id="card-mass-marketing" class="lecture-interactive-card" data-lecture-section="card_mass_marketing" style="background: #ffffff; border: 1.5px solid #cbd5e1; border-radius: 12px; padding: 22px; cursor: pointer; transition: all 0.2s; box-shadow: 0 2px 6px rgba(0,0,0,0.02);">
            <div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 10px;">
                <h3 style="color: #2563eb; font-size: 18px; margin: 0;">🌎 Mass Marketing (Standardized Market)</h3>
                <span style="background: #eff6ff; color: #1d4ed8; padding: 4px 10px; border-radius: 6px; font-size: 12px; font-weight: bold;">High Volume</span>
            </div>
            <p style="font-size: 14px; color: #475569; margin: 0 0 12px 0;">Selling a standardized product to the entire market without targeting subgroups (e.g. toothpaste, soft drinks).</p>
            <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 12px;">
                <div style="background: #f0fdf4; border: 1px solid #bbf7d0; padding: 12px; border-radius: 8px;">
                    <b style="color: #15803d; font-size: 13.5px;">✅ Advantages:</b>
                    <ul style="margin: 4px 0 0 0; padding-left: 18px; font-size: 13px; color: #166534; line-height: 1.4;">
                        <li>Massive sales volume generates high total sales revenue.</li>
                        <li>Substantial economies of scale lower average unit costs.</li>
                        <li>Risks spread across widespread customer demographics.</li>
                    </ul>
                </div>
                <div style="background: #fef2f2; border: 1px solid #fecaca; padding: 12px; border-radius: 8px;">
                    <b style="color: #b91c1c; font-size: 13.5px;">❌ Disadvantages:</b>
                    <ul style="margin: 4px 0 0 0; padding-left: 18px; font-size: 13px; color: #991b1b; line-height: 1.4;">
                        <li>Intense cutthroat price competition from market rivals.</li>
                        <li>High advertising costs required to establish brand recall.</li>
                        <li>Standardized products cannot satisfy individual tastes.</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <!-- 4. MARKET SEGMENTATION -->
    <div id="sec-segmentation" class="lecture-interactive-card" data-lecture-section="sec_segmentation" style="margin-bottom: 45px; padding: 22px 24px; background: #ffffff; border: 1px solid #e2e8f0; border-radius: 14px; box-shadow: 0 2px 8px rgba(0,0,0,0.02); cursor: pointer; transition: all 0.2s;">
        <h2 style="color: #0f172a; border-bottom: 3px solid #10b981; padding-bottom: 12px; margin-bottom: 14px; display: inline-block; font-size: 24px; line-height: 1.2; margin-top: 0;">🧩 4. MARKET SEGMENTATION</h2>
        <div style="background: #f0fdf4; border-left: 5px solid #10b981; padding: 14px 18px; border-radius: 8px; font-size: 15px; color: #065f46; line-height: 1.6; margin-bottom: 16px;">
            <b>Market segmentation</b> is the division of a broad market into distinct subgroups of consumers sharing similar needs or characteristics.
        </div>
        <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 14px;">
            <div style="background: #f8fafc; border: 1px solid #cbd5e1; border-radius: 8px; padding: 16px;">
                <b style="color: #0f766e; font-size: 15px;">💵 By Income / Social Class:</b>
                <p style="margin: 5px 0 0 0; font-size: 13.5px; color: #475569;">Targeting high-earners (luxury designer watches) vs budget families (discount supermarket goods).</p>
            </div>
            <div style="background: #f8fafc; border: 1px solid #cbd5e1; border-radius: 8px; padding: 16px;">
                <b style="color: #0f766e; font-size: 15px;">👶 By Age Group:</b>
                <p style="margin: 5px 0 0 0; font-size: 13.5px; color: #475569;">Customized offerings for infants, teenagers, young professionals, and retired seniors.</p>
            </div>
            <div style="background: #f8fafc; border: 1px solid #cbd5e1; border-radius: 8px; padding: 16px;">
                <b style="color: #0f766e; font-size: 15px;">🌍 By Geographic Region:</b>
                <p style="margin: 5px 0 0 0; font-size: 13.5px; color: #475569;">Urban versus rural consumers; cold climate apparel versus tropical beachwear.</p>
            </div>
            <div style="background: #f8fafc; border: 1px solid #cbd5e1; border-radius: 8px; padding: 16px;">
                <b style="color: #0f766e; font-size: 15px;">🚻 By Gender:</b>
                <p style="margin: 5px 0 0 0; font-size: 13.5px; color: #475569;">Developing distinct fragrances, personal care, and fashion lines for male and female demographics.</p>
            </div>
        </div>
    </div>

    <!-- 5. RECOMMEND AND JUSTIFY (CAMBRIDGE EXAM STRATEGY) -->
    <div id="sec-recommend-segmentation" class="lecture-interactive-card" data-lecture-section="sec_recommend_segmentation" style="margin-bottom: 45px; background: #eff6ff; border: 2px solid #bfdbfe; border-radius: 14px; padding: 24px; cursor: pointer; transition: all 0.2s; box-shadow: 0 2px 8px rgba(0,0,0,0.02);">
        <h2 style="color: #1e3a8a; border-bottom: 3px solid #3b82f6; padding-bottom: 12px; margin-bottom: 14px; font-size: 22px; margin-top: 0; display: inline-block;">
            🎯 5. HOW TO RECOMMEND &amp; JUSTIFY MARKET SEGMENTATION (Cambridge Exam Strategy)
        </h2>
        <p style="font-size: 15px; color: #1e40af; margin-bottom: 16px; line-height: 1.6;">
            Paper 1 &amp; 2 questions frequently ask candidates to recommend the best segmentation method for an enterprise:
        </p>
        <div style="background: #ffffff; border: 1px solid #bfdbfe; border-radius: 8px; padding: 16px 20px;">
            <b style="color: #1e40af; font-size: 15px;">💡 Cambridge Segmentation Evaluation Framework:</b>
            <ol style="margin: 8px 0 0 0; padding-left: 20px; font-size: 13.5px; color: #334155; line-height: 1.6;">
                <li><b>Identify target product characteristics:</b> Does the product cater to high wealth, young youth culture, or regional climate?</li>
                <li><b>Select the optimal segmentation base:</b> Justify whether income, age, or location maximizes targeted appeal.</li>
                <li><b>Explain budget efficiency:</b> Detail how segmentation avoids wasted advertising expenditure on uninterested groups.</li>
                <li><b>Align the Marketing Mix (4Ps):</b> Show how the chosen segment guides suitable pricing, promotion, and distribution channels.</li>
            </ol>
        </div>
    </div>

</div>"""
    return html

# ==============================================================================
# 3. GENERATE NEW HTML FOR PAGE 2 (BILINGUAL)
# ==============================================================================
def build_page_2_html(original_p2):
    header_banner = """<div style="margin-bottom: 35px; padding: 22px 26px; background: linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%); border-radius: 14px; border: 1px solid #e2e8f0; box-shadow: 0 2px 6px rgba(0,0,0,0.02);">
        <div>
            <span style="font-size: 12px; font-weight: 700; color: #0284c7; text-transform: uppercase; letter-spacing: 0.8px;">Cambridge IGCSE Business Studies (0450) • Song Ngữ Anh - Việt</span>
            <h1 style="margin: 4px 0 0 0; font-size: 26px; color: #0f172a; font-weight: 800; line-height: 1.2;">3.1 Marketing, Competition and the Customer (Tiếp thị, Cạnh tranh &amp; Khách hàng)</h1>
        </div>
    </div>"""
    pattern = r'(<div style="font-family: \'Segoe UI\', Arial, sans-serif; width: 100%; margin: 20px auto; color: #334155; line-height: 1.6; box-sizing: border-box;">)'
    new_p2 = re.sub(pattern, r'\1\n\n    ' + header_banner, original_p2, count=1)
    return new_p2

async def main():
    print(f"=== Rebuilding Business Studies 3.1 Audio and HTML ===")
    
    audio_dir = os.path.join(os.path.dirname(__file__), '..', 'public', 'audio', 'lectures', 'business', CODE)
    os.makedirs(audio_dir, exist_ok=True)

    # 1. Generate audio files and write manifest.json
    print(f"\nGenerating {len(segments)} audio segments...")
    manifest = await process_lecture_audio(CODE, LID, COURSE_TITLE, TITLE, segments, major_sections, subject='business')
    
    # 2. Build Page 1 HTML
    p1_html = build_page_1_html()
    diff1 = len(p1_html.split('<div')) - len(p1_html.split('</div>'))
    print(f"\nPage 1 HTML div diff: {diff1}")
    if diff1 != 0:
        raise ValueError(f"Page 1 has div balance error: {diff1}")
        
    # 3. Build Page 2 HTML
    with open('scripts/raw_pages/3_1_p2.html', 'r', encoding='utf-8') as f:
        orig_p2 = f.read()
    p2_html = build_page_2_html(orig_p2)
    diff2 = len(p2_html.split('<div')) - len(p2_html.split('</div>'))
    print(f"Page 2 HTML div diff: {diff2}")
    if diff2 != 0:
        raise ValueError(f"Page 2 has div balance error: {diff2}")
        
    # 4. Update Supabase
    print("\nUpdating Supabase page 1...")
    res1 = sb.table('lecture_pages').update({'content_html': p1_html}).eq('lecture_id', LID).eq('page_number', 1).execute()
    print(f"Page 1 updated: {len(res1.data)} rows.")
    
    print("Updating Supabase page 2...")
    res2 = sb.table('lecture_pages').update({'content_html': p2_html}).eq('lecture_id', LID).eq('page_number', 2).execute()
    print(f"Page 2 updated: {len(res2.data)} rows.")
    
    print("\n✅ REBUILD 3.1 COMPLETED SUCCESSFULLY!")

if __name__ == '__main__':
    asyncio.run(main())
